model = "gpt-5.1-codex"
model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

model_reasoning_summary_format = "experimental"

notify = ["bash", "/Users/dkuro/.codex/scripts/notify.sh"]

[features]
rmcp_client = true
web_search_request = true

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]
startup_timeout_ms = 30000
