model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"
hide_agent_reasoning = true
network_access = true

model_reasoning_summary_format = "experimental"

notify = ["bash", "/Users/dkuro/.codex/scripts/notify.sh"]

[features]
rmcp_client = true
web_search_request = true
skills = true

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
