[tools]
go = "latest"
node = "24"
bun = "latest"
python = "3.14.0"
rust = "latest"
java = "latest"

"npm:typescript" = "latest"
"npm:prettier" = "latest"
"npm:pnpm" = "latest-10"

"cargo:eza" = "latest"

"cargo:https://github.com/openai/codex.git" = { version = "tag:rust-v0.51.0-alpha.6", crate = "codex-cli" }

"npm:@google/gemini-cli" = "latest"

# Claude Code
"npm:ccusage" = "latest"
"pipx:claude-monitor" = "latest"

# Git diffs
"npm:difit" = "latest"
"cargo:git-delta" = "latest"

"cargo:similarity-ts" = "latest"
"cargo:similarity-generic" = "latest"

